version: '3.8'

services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - frontend:/app/build  
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  
  frontend:
    build: 
      context: ./frontend  
      dockerfile: Dockerfile
    volumes:
    - frontend:/app/build
    networks:
      - app-network
    environment:
    - REACT_APP_API_URL=http://backend:8080
    

  
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    expose:
      - "8080"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/foodsprint?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  
  db:
    image: mysql:8.0
    expose:
      - "3306"  
    environment:
      - MYSQL_DATABASE=foodsprint
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  frontend: