apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "foodsprint.ddns-ip.net"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: react-cluster-ip
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: springboot-cluster-ip
                port:
                  number: 8080
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: springboot-cluster-ip
                port:
                  number: 8080
