apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      component: springboot
  template:
    metadata:
      labels:
        component: springboot
    spec:
      containers:
        - name: springboot
          image:
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: springboot-config
          imagePullPolicy: Always
